### ISSUE TITLE
Gameplay discussion

### ISSUE THREAD

**Issue by cc1778** [CS3398-Bronze-Statues/CS3398-Bronze-S2017#15]
As game developers, we need to determine what kind of gameplay will be featured in our game so that we can properly build the story around it.  This includes:  what kind of battles/fights if any, what kind of NPC interaction, what kind of traveling etc.

**Comment by amh231** [comment]
I've added a file in the 'Story Development' folder called 'Gameplay'. This was a brainstorming session summary of our gameplay mechanics. The summary was generated via Slack communication and after class meet-ups.
