### ISSUE TITLE
Hero Creation

### ISSUE THREAD

**Issue by amh231** [CS3398-Bronze-Statues/CS3398-Bronze-S2017#36]
Discuss the attributes of our hero/heroine

**Comment by cc1778** [comment]
We are dropping this work from sprint 1 because we underestimated our python learning tasks which took much more time than anticipated.  As a result, we spent a large amount of time learning python, and did not have time to complete all of the framework discussion.

**Comment by cc1778** [comment]
Moving this to closed because it is covered in another task.
