### ISSUE TITLE
Kevin's Code Academy - Python Learning I

### ISSUE THREAD

**Issue by amh231** [CS3398-Bronze-Statues/CS3398-Bronze-S2017#38]

**Comment by krodbobcat** [comment]
The Python courses on Codeacademy.com will help learn the language in preparation for developing our desktop game.

**Comment by krodbobcat** [comment]
![python progress](https://cloud.githubusercontent.com/assets/25235517/23136763/d11ce764-f763-11e6-951b-8a913a0d869d.jpg)

This shows my current progress on the Python course from codeacademy.com. I am currently more than 1/4 of the way done.

**Comment by krodbobcat** [comment]
`"""
Kevin's Python Learning I

Topics covered are Python syntax, String and Console Output, Conditionals and Control Flow.
Below are various examples of what I learned on codeacademy.com
"""

#Example of a variable
variable_example = "example"

#Example of variable output
print variable_example

#Example of string output
print "print this string"

#Example of boolean variables
bool_1 = True
bool_2 = False

#Example of condition statement
if 3 > 1:
    print "This is true"
else:
    print "This is false"

#Example of advanced string output/string concatenation
pi = 3.14
print str(3.14) + " - This is the value of PI"

#Example of math operations
addition = 3 + 4
print addition

exponent = 2 ** 2
print exponent

#Example of boolean operators
if 3 == 1 and 4 < 1:
    print "This is not true"
elif -4 < 1 and 7 > 1:
    print "This is true"
else:
    print "Nothing"

bad = False
good = True

if good:
    print "Good"
elif false:
    print "Bad"
else:
    print "Nada"
`

This is the code I made as an example of what I learned for this task/issue.
