### ISSUE TITLE
Kevins's Code Academy - Python Learning II

### ISSUE THREAD

**Issue by amh231** [CS3398-Bronze-Statues/CS3398-Bronze-S2017#39]

**Comment by krodbobcat** [comment]
The Python courses on Codeacademy.com will help learn the language in preparation for developing our desktop game. This is a continuation of Python Learning I.

**Comment by krodbobcat** [comment]
![python progress](https://cloud.githubusercontent.com/assets/25235517/23136889/83ebf984-f764-11e6-8b6a-392c0f18d293.jpg)

I am currently 33% of the way done with the Python course on Code Academy. I am on the lesson dealing with Functions.

**Comment by krodbobcat** [comment]
![python progress](https://cloud.githubusercontent.com/assets/25235517/23144448/4c7b7686-f78d-11e6-9aa8-97688559af8d.jpg)

I am now 42% of the way done with the Python courses.

**Comment by krodbobcat** [comment]
![python progress](https://cloud.githubusercontent.com/assets/25235517/23383603/e592b7f6-fd0c-11e6-86f5-ecc4e9b5bef3.jpg)

Currently 47% of the way done with the Python courses.
