### ISSUE TITLE
Kevin's Code Academy - Python Learning III

### ISSUE THREAD

**Issue by amh231** [CS3398-Bronze-Statues/CS3398-Bronze-S2017#40]
Learn Python

**Comment by krodbobcat** [comment]
The Python courses on Codeacademy.com will help learn the language in preparation for developing our desktop game. This is a continuation of Python Learning II.

**Comment by krodbobcat** [comment]
![python progress](https://cloud.githubusercontent.com/assets/25235517/23383636/0eb6da4a-fd0d-11e6-87a0-bc07777a3305.jpg)

Currently 47% of the way done with the Python Codeacademy course.

**Comment by krodbobcat** [comment]
![python progress](https://cloud.githubusercontent.com/assets/25235517/23394551/7ad3b5ee-fd4f-11e6-8f39-71866429aa55.jpg)

Currently 52% of the way done with the Python Codeacademy course.

**Comment by krodbobcat** [comment]
![python progress](https://cloud.githubusercontent.com/assets/25235517/23484947/d449a2a0-fe9e-11e6-80be-7a6c91e44795.jpg)

Currently 71% of the way done with Python courses.
