### ISSUE TITLE
Kevin's Code Academy - Python Learning IV

### ISSUE THREAD

**Issue by amh231** [CS3398-Bronze-Statues/CS3398-Bronze-S2017#41]
Learn Python

**Comment by krodbobcat** [comment]
The Python courses on Codeacademy.com will help learn the language in preparation for developing our desktop game. This is a continuation of Python Learning III.

**Comment by krodbobcat** [comment]
![python progress](https://cloud.githubusercontent.com/assets/25235517/23484991/162f857c-fe9f-11e6-9d90-00340981a267.jpg)

Currently 71% done with the Python Codeacademy course.

**Comment by krodbobcat** [comment]
![python progress](https://cloud.githubusercontent.com/assets/25235517/23495930/e8595802-fee0-11e6-9222-4e72d4dd7f40.jpg)

100% complete on the Python Codeacademy course.
