### ISSUE TITLE
Character Background

### ISSUE THREAD

**Issue by amh231** [CS3398-Bronze-Statues/CS3398-Bronze-S2017#43]

**Comment by cc1778** [comment]
We are dropping this work from sprint 1 because we underestimated our python learning tasks which took much more time than anticipated.  As a result, we spent a large amount of time learning python, and did not have time to complete all of the framework discussion.

**Comment by amh231** [comment]
Changing the estimate to better accommodate the task.

**Comment by cbFowler** [comment]
Completed character descriptions. This outlines the various game characters and their roles. Information compiled in GameCharacterDescription.docx found here: https://github.com/CS3398-Bronze-Statues/CS3398-Bronze-S2017/tree/develop/Story%20Development
