### ISSUE TITLE
Item/Inventory Description

### ISSUE THREAD

**Issue by amh231** [CS3398-Bronze-Statues/CS3398-Bronze-S2017#50]
What items will be used in our Inventory?

**Comment by mcs152** [comment]
Completed Item/Inventory description. This is a rough draft and can be changed ! File(ItemInventoryDescription.docx) can be found here:  https://github.com/CS3398-Bronze-Statues/CS3398-Bronze-S2017/blob/develop/Story%20Development/ItemInventoryDescription.docx
