### ISSUE TITLE
String Parser

### ISSUE THREAD

**Issue by cc1778** [CS3398-Bronze-Statues/CS3398-Bronze-S2017#51]
We need a string parser to interpret the commands given by the user.

**Comment by amh231** [comment]
1. Unit Test: Directional Input

- Input: move North
- Output: User moves into new zone, if not, zone is not available.

2. Unit test: Special characters/Unavailable Moves

- Input: op3n L33t $tuff
- Output: [Error Message] "Not a valid command"

3. Unit test: No input (detects new line character)

- Input : >
  >

- Output: 
 > (Waiting on command)

4. Unit test: Help Command

- Input : help

- Output: displays a list of commands available

**Comment by cc1778** [comment]
The initial implementation of the string parser is done and uploaded.  It is still just a template due to the fact that many details of the game are not solidified.  There will be a large integration phase for all of the code in sprint 3 to make everything work together properly.
